"use strict";
const assert=require("node:assert/strict");
const {rozszerz,porownaj,filtruj,jezykOpisu,jezykAutora}=require("../app/research-silnik");
const {licznik,adresCDN}=require("../moduly/research-publiczne");
const {normalizuj,analiza,obsluzOdkrywanie}=require("../moduly/research-odkrywanie");
async function test(){
 assert.deepEqual(rozszerz("hipertrofia","en").frazy,["hypertrophy","muscle growth"]);
 assert.deepEqual(rozszerz("budowanie sylwetki","en").frazy,["muscle growth","hypertrophy","body recomposition"]);
 assert.equal(rozszerz("budowanie sylwetki","both").frazy.length,6);
 assert.deepEqual(rozszerz("  FITNESS  ","both").frazy,["fitness","trening siłowy","workout","strength training","muscle growth"]);
 assert(rozszerz("budowanie    sylwetki").przetlumaczone);
 assert.equal(jezykOpisu("カッコイイ体を作る時短トレーニング初心者におすすめです"),"inne");
 assert.notEqual(jezykOpisu("हर Workout में बस Weight बढ़ाने के पीछे मत भागो। Muscle Growth के लिए सिर्फ Heavy Weight नहीं #workout #training #muscle #growth #your"),"en");
 assert.equal(jezykOpisu("#muscle #growth #training #workout"),null);
 // Hiszpanski, portugalski, niemiecki, francuski, wloski, turecki, indonezyjski i hindi zapisane lacinka to "inne".
 for(const opis of ["Rutina de hipertrofia para piernas 🔥 #gym #hipertrofia","Treino de hipertrofia para pernas. Salva esse vídeo!","Das beste Training für Muskelaufbau, wenn du wenig Zeit hast","Le meilleur entrainement pour les jambes sans matériel","Il miglior allenamento per le gambe che puoi fare a casa","Bacak kası için en iyi antrenman","Latihan otot kaki yang bisa kamu lakukan di rumah","Bhai roz gym jao aur sahi diet lo, muscle growth ke liye yeh zaruri hai","Лучшая тренировка для ног #hypertrophy","#treino #academia #hipertrofia"])assert.equal(jezykOpisu(opis),"inne",opis);
 // Krotkie polskie i angielskie opisy oraz polskie hashtagi.
 for(const opis of ["Zapisz sobie na później 💪 #hipertrofia","Najlepszy trening na masę, który możesz zrobić w domu","3 ćwiczenia na plecy","#trening #siłownia #hipertrofia"])assert.equal(jezykOpisu(opis),"pl",opis);
 for(const opis of ["Save this for later 💪 #hipertrofia","3 exercises for back growth","How to train legs when you have no time"])assert.equal(jezykOpisu(opis),"en",opis);
 // Same uniwersalne tagi, sama nazwa tematu albo pusty opis: brak danych, nie zgadujemy.
 for(const opis of ["#gym #fitness #hipertrofia","Hipertrofia","",null,"🔥🔥🔥"])assert.equal(jezykOpisu(opis),null,String(opis));
 // Jezyk autora: minimum 3 rozpoznane opisy i 60% przewagi; szacunki z historii nie licza sie ponownie.
 assert.equal(jezykAutora([{jezyk:"inne"},{jezyk:"inne"},{jezyk:"inne"},{jezyk:null},{jezyk:"en"}]),"inne");
 assert.equal(jezykAutora([{jezyk:"pl"},{jezyk:"pl"},{jezyk:null}]),null);
 assert.equal(jezykAutora([{jezyk:"pl"},{jezyk:"en"},{jezyk:"pl"},{jezyk:"en"}]),null);
 assert.equal(jezykAutora([{jezyk:"pl"},{jezyk:"pl"},{jezyk:"pl",jezyk_zrodlo:"autor"}]),null);
 assert.equal(jezykAutora([{jezyk:"en"},{jezyk:"en"},{jezyk:"en"},{jezyk:"pl"}]),"en");
 assert.deepEqual(rozszerz("nowy temat","both"),{frazy:["nowy temat"],przetlumaczone:false});
 assert.equal(licznik("1,2 mln"),1200000);assert.equal(licznik("753 tys."),753000);assert.equal(licznik("1,234"),1234);assert.equal(licznik(null),null);assert.equal(licznik("polubienia 200"),null);
 assert.equal(adresCDN("https://fbcdn.net.evil.test/v.mp4"),"");assert.equal(adresCDN("http://scontent.cdninstagram.com/a"),"");
 assert.equal(jezykOpisu("Your muscle growth and training: the workout for you"),"en");assert.equal(jezykOpisu("#fitness"),null);
 const historia=Array.from({length:6},(_,i)=>({id:String(i),username:"trener",typ:"rolka",zrodlo_historii:"profil",wyswietlenia:10000,data:`2026-09-${10+i}T10:00:00Z`}));
 const post={id:"test",username:"trener",typ:"rolka",wyswietlenia:50000,data:"2026-09-23T10:00:00Z",jezyk:"pl"};
 assert.equal(porownaj(post,[...historia,post,{...historia[0],id:"pozniej",wyswietlenia:900000,data:"2026-09-24T10:00:00Z"}]).krotnosc_wyswietlen,5);
 assert.equal(porownaj(post,[...historia.slice(0,4),historia[0]]).krotnosc_wyswietlen,null);
 assert.equal(porownaj(post,historia.map(p=>({...p,zrodlo_historii:"popular"}))).krotnosc_wyswietlen,null);
 assert.equal(porownaj(post,historia.map(p=>({...p,wyswietlenia:0}))).krotnosc_wyswietlen,null);
 const f={jezyk:"both",prog:3,okres:7,niepelne:false}, teraz=Date.parse("2026-09-24T10:00:00Z");
 assert.equal(filtruj([{...post,...porownaj(post,historia)}],f,teraz).posty.length,1);
 assert.equal(filtruj([{...post,data:null,krotnosc_wyswietlen:null}],f,teraz).posty.length,0);
 assert.equal(filtruj([{...post,data:null,krotnosc_wyswietlen:null}],{...f,niepelne:true},teraz).posty[0].braki_filtrow.length,2);
 assert.equal(filtruj([{...post,krotnosc_wyswietlen:2}],{...f,niepelne:true},teraz).posty.length,0);
 const p=normalizuj({kod:"Abcdefgh",opis:"Your muscle growth: what works? Save this workout for your training.",licznik:"50 tys.",miniatura:"javascript:alert(1)",film:"https://evil.test/a",data:null},"muscle growth","https://www.instagram.com/popular/muscle-growth/");
 assert.equal(p.udostepnienia,null);assert.equal(p.komentarze,null);assert.equal(p.miniatura,"");assert.equal(p.film,"");assert.equal(p.data,null);
 assert.equal(normalizuj({kod:"__proto__"},"x",""),null);
 assert.match(analiza(p,{odbiorcy:"trenujący"}).zakres,/Bez oglądania/);
 const pamiec=new Map();let wywolania=0;const n={sciezki:{dane:"test"},czytajJson:(p,d)=>structuredClone(pamiec.get(p)??d),zapiszJson:(p,d)=>pamiec.set(p,structuredClone(d)),odpowiedzJson:(r,k,d)=>{r.kod=k;r.dane=structuredClone(d)},czytajCialo:async r=>r.cialo,pobierzPubliczne:async f=>{wywolania++;return{url:"https://www.instagram.com/popular/"+f+"/",posty:[{kod:"Abcdefgh",opis:p.opis,licznik:"50 tys."}]}}};
 async function api(trasa="",cialo){const r={};await obsluzOdkrywanie({method:cialo===undefined?"GET":"POST",cialo},r,new URL("http://localhost/api/research/odkrywanie"+trasa),n);return r}
 n.pobierzSzczegoly=async()=>({data:"2026-01-01T00:00:00Z",polubienia:23,komentarze:4,zrodlo_szczegolow:"https://www.instagram.com/reel/Abcdefgh/"});
 n.pobierzProfil=async()=>{throw new Error("Nie wolno pobierac profilu dla starego posta")};
 assert.equal((await api("/szukaj",{temat:"x",frazy:[]})).kod,400);
 assert.equal((await api("/szukaj",{temat:"x",frazy:["muscle growth"]})).kod,202);
 for(let i=0;i<20&&(await api()).dane.postep.w_toku;i++)await new Promise(r=>setTimeout(r,1));
 assert.equal((await api()).dane.posty.length,1);
 assert.equal((await api()).dane.posty[0].komentarze,4);assert.equal((await api()).dane.posty[0].data,"2026-01-01T00:00:00Z");
 assert.equal((await api("/zapisz",{id:"Abcdefgh",zapisana:true})).kod,200);
 assert.equal((await api("/notatka",{id:"Abcdefgh",tekst:"Mój pomysł <script>"})).kod,200);
 assert.equal((await api("/profil",{kim:"trener",odbiorcy:"plateau",tematy:"sylwetka"})).kod,200);
 assert.equal((await api("/analiza",{id:"Abcdefgh"})).dane.profil.odbiorcy,"plateau");
 assert.equal((await api("/zapisz",{id:"__proto__",zapisana:true})).kod,404);
 await api("/szukaj",{temat:"x",frazy:["muscle growth"]});await new Promise(r=>setTimeout(r,5));assert.equal(wywolania,1);
 assert.equal((await api()).dane.notatki.Abcdefgh,"Mój pomysł <script>");
 n.pobierzPubliczne=async()=>{throw new Error("transport with private value")};
 await api("/szukaj",{temat:"błąd",frazy:["nowa fraza"]});await new Promise(r=>setTimeout(r,5));
 const poBledzie=(await api()).dane;
 assert.equal(poBledzie.wyszukiwanie.stan,"blad");assert.deepEqual(poBledzie.ostatnie,[]);assert.equal(poBledzie.wyszukiwanie.temat,"błąd");
 assert.equal(poBledzie.postep.w_toku,false);assert.equal(poBledzie.postep.bledy[0].blad,"Nie udało się pobrać tej frazy.");assert.deepEqual(poBledzie.zapisane,["Abcdefgh"]);assert.equal(poBledzie.notatki.Abcdefgh,"Mój pomysł <script>");
 let proby=0;n.pobierzPubliczne=async()=>{proby++;throw Object.assign(new Error("Instagram zatrzymał odczyt"),{blokada:true})};
 await api("/szukaj",{temat:"blokada",frazy:["blokada jeden","blokada dwa"]});await new Promise(r=>setTimeout(r,5));assert.equal(proby,1);assert.equal((await api()).dane.postep.w_toku,false);
 const terazMs=Date.now();
 n.pobierzPubliczne=async()=>({url:"https://www.instagram.com/popular/nowy/",posty:[{kod:"FreshAA",username:"autor",opis:p.opis,licznik:"50 tys."}]});
 n.pobierzSzczegoly=async id=>({data:new Date(terazMs-(id==="FreshAA"?1:Number(id.slice(-1))+2)*86400000).toISOString(),polubienia:100,komentarze:12});
 n.pobierzProfil=async()=>({url:"https://www.instagram.com/autor/reels/",posty:Array.from({length:6},(_,i)=>({kod:"OlderA"+i,username:"autor",licznik:"10 tys."}))});
 await api("/szukaj",{temat:"nowy",frazy:["nowy"]});for(let i=0;i<30&&(await api()).dane.postep.w_toku;i++)await new Promise(r=>setTimeout(r,1));
 const nowy=(await api()).dane.posty.find(p=>p.id==="FreshAA");assert.equal(nowy.krotnosc_wyswietlen,5);assert.equal(nowy.liczba_bazowych,6);assert.equal(nowy.komentarze,12);
 n.pobierzPubliczne=async()=>{throw Object.assign(new Error("Instagram nie udostępnia tej strony."),{kod:"STRONA_NIEDOSTEPNA"})};
 await api('/szukaj',{temat:'fitness',frazy:['fitness']});for(let i=0;i<30&&(await api()).dane.postep.w_toku;i++)await new Promise(r=>setTimeout(r,1));
 assert.equal((await api()).dane.postep.bledy[0].kod,'STRONA_NIEDOSTEPNA');
 delete require.cache[require.resolve('../moduly/research-odkrywanie')];const swiezy=require('../moduly/research-odkrywanie'),res={};
 await swiezy.obsluzOdkrywanie({method:'GET'},res,new URL('http://localhost/api/research/odkrywanie'),n);
 assert.equal(res.dane.wyszukiwanie.stan,'blad');assert.equal(res.dane.postep.bledy[0].kod,'STRONA_NIEDOSTEPNA','Błąd źródła nie znika po restarcie');
 // Migracja zapisanych danych do wersji 3: stare "nieznane" hiszpanskie opisy staja sie "inne", a rolki bez opisu dostaja jezyk autora.
 const stareDane={wersja_jezyka:2,posty:{Es000001:{id:"Es000001",username:"hiszpan",opis:"Rutina de hipertrofia para piernas",jezyk:null,data:"2026-09-20T00:00:00Z"},Es000002:{id:"Es000002",username:"hiszpan",opis:"#hipertrofia 🔥",jezyk:null,data:"2026-09-21T00:00:00Z"}},historie:{hiszpan:{posty:Array.from({length:4},(_,i)=>({id:"H"+i,username:"hiszpan",opis:"Entrenamiento de piernas que puedes hacer en casa",jezyk:null,data:"2026-09-0"+(i+1)+"T00:00:00Z"}))}},ostatnie:["Es000001","Es000002"],wyszukiwanie:{filtry:{jezyk:"both",okres:30,prog:0}}};
 const pamiec2=new Map([["migracja/research_odkrywanie.json",stareDane]]),n2={sciezki:{dane:"migracja"},czytajJson:(p,d)=>structuredClone(pamiec2.get(p)??d),zapiszJson:(p,d)=>pamiec2.set(p,structuredClone(d)),odpowiedzJson:(r,k,d)=>{r.kod=k;r.dane=structuredClone(d)}};
 const res2={};await swiezy.obsluzOdkrywanie({method:'GET'},res2,new URL('http://localhost/api/research/odkrywanie'),n2);
 const poMigracji=pamiec2.get("migracja/research_odkrywanie.json");
 assert.equal(poMigracji.wersja_jezyka,3);assert.equal(poMigracji.posty.Es000001.jezyk,"inne");assert.equal(poMigracji.posty.Es000001.jezyk_zrodlo,undefined);
 assert.equal(poMigracji.posty.Es000002.jezyk,"inne");assert.equal(poMigracji.posty.Es000002.jezyk_zrodlo,"autor");assert.equal(poMigracji.historie.hiszpan.jezyk_autora,"inne");
 assert.equal(poMigracji.wyszukiwanie.potwierdzone,0);
 console.log("OK: frazy, język, brakujące dane, poprzednie rolki/mediana, filtry, walidacja, zapis, cache, zakres analizy, języki i migracja");
}
test().catch(e=>{console.error(e);process.exitCode=1});
